#!/bin/bash

set -e

bundle exec jekyll build
bundle exec htmlproofer ./_site --check-html --check-sri
bundle exec rubocop -D --config .rubocop.yml
bundle exec ruby ./validate-html
gem build jekyll-theme-tactile.gemspec
